services:
  json-server:
    image: vimagick/json-server
    command: -h 0.0.0.0 -p 3000 -s ./js db.json
    init: true
    ports:
      - "3000:3000"
    volumes:
      - ./js:/data
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./:/usr/share/nginx/html 
    restart: always
    ports:
      - 8080:80


  